### PR TITLE
Update to new metanorma structure

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Syntax is correct. This is an error somewhere in the processing chain.

Ping @opoudjis @andrew2net 

Failure:

```
[info]: Compiling /Users/me/src/rfc-camelot-holy-grenade/sources/draft-camelot-holy-grenade.adoc ...
[relaton] Info: detecting backends:
[relaton] RFC8140 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN, W3C, IEEE, IHO, BIPM, ECMA, CIE, BSI, CEN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma)
Traceback (most recent call last):
	67: from /Users/me/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
	66: from /Users/me/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
	65: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
	64: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	63: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
	62: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
	61: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	60: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
	59: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	58: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	57: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	56: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
	55: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
	54: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
	53: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
	52: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma:23:in `<top (required)>'
	51: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma:23:in `load'
	50: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/exe/metanorma:20:in `<top (required)>'
	49: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli.rb:34:in `start'
	48: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	47: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	46: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	45: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	44: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	43: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	42: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	41: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	40: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	38: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	37: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/commands/site.rb:25:in `generate'
	36: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:23:in `generate'
	35: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:28:in `generate'
	34: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:28:in `each'
	33: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
	32: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:81:in `compile'
	31: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/compiler.rb:35:in `compile'
	30: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/compiler.rb:30:in `compile'
	29: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	28: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.3/lib/metanorma/compile.rb:26:in `compile'
	27: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.3/lib/metanorma/compile.rb:93:in `process_input'
	26: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.3/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	25: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.3/lib/metanorma/input/asciidoc.rb:24:in `process'
	24: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:119:in `convert'
	23: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:944:in `convert'
	22: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	21: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/base.rb:161:in `document'
	20: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-ietf-2.3.2/lib/asciidoctor/ietf/converter.rb:26:in `makexml'
	19: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/base.rb:196:in `makexml'
	18: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-ietf-2.3.2/lib/asciidoctor/ietf/converter.rb:118:in `cleanup'
	17: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/cleanup.rb:43:in `cleanup'
	16: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/cleanup_ref.rb:153:in `bibitem_cleanup'
	15: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/cleanup_ref_dl.rb:8:in `ref_dl_cleanup'
	14: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
	13: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
	12: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
	11: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/cleanup_ref_dl.rb:11:in `block in ref_dl_cleanup'
	10: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/bibliographic_item.rb:263:in `from_hash'
	 9: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:25:in `hash_to_bib'
	 8: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:180:in `contributors_hash_to_bib'
	 7: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:180:in `each_with_index'
	 6: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:180:in `each'
	 5: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:192:in `block in contributors_hash_to_bib'
	 4: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:215:in `person_hash_to_bib'
	 3: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:229:in `fullname_hash_to_bib'
	 2: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:470:in `localname'
	 1: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:470:in `new'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/localized_string.rb:26:in `initialize': invalid LocalizedString content type: String (ArgumentError)
me:~/src/rfc-camelot-holy-grenade (rt-update-metanorma): 
```

**Comment by andrew2net** [comment]
@ronaldtse relaton needs prefix be separated by space to recognize it. I.e. the reference `RFC8140` should be `RFC 8140`.

**Comment by ronaldtse** [comment]
@andrew2net that is not the issue here, the failure is in another place.

Here's one with the `:updates: RFC8140` changed to `:updates: IETF RFC 8140` (~~I don't think this is well documented @opoudjis that it takes a new ref~~ actually documented [here](https://www.metanorma.org/author/ietf/ref/document-attributes/))

```
[info]: Compiling /Users/me/src/rfc-camelot-holy-grenade/sources/draft-camelot-holy-grenade.adoc ...
[relaton] Info: detecting backends:
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma)
Traceback (most recent call last):
	67: from /Users/me/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
	66: from /Users/me/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
	65: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
	64: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	63: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
	62: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
	61: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	60: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
	59: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	58: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	57: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	56: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
	55: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
	54: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
	53: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
	52: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma:23:in `<top (required)>'
	51: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma:23:in `load'
	50: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/exe/metanorma:20:in `<top (required)>'
	49: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli.rb:34:in `start'
	48: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	47: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	46: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	45: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	44: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	43: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	42: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	41: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	40: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
	38: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	37: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/commands/site.rb:25:in `generate'
	36: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:23:in `generate'
	35: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:28:in `generate'
	34: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:28:in `each'
	33: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
	32: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/site_generator.rb:81:in `compile'
	31: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/compiler.rb:35:in `compile'
	30: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/compiler.rb:30:in `compile'
	29: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.9/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	28: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.3/lib/metanorma/compile.rb:26:in `compile'
	27: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.3/lib/metanorma/compile.rb:93:in `process_input'
	26: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.3/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	25: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.3.3/lib/metanorma/input/asciidoc.rb:24:in `process'
	24: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.15/lib/asciidoctor/convert.rb:119:in `convert'
	23: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:944:in `convert'
	22: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	21: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/base.rb:161:in `document'
	20: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-ietf-2.3.2/lib/asciidoctor/ietf/converter.rb:26:in `makexml'
	19: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/base.rb:196:in `makexml'
	18: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-ietf-2.3.2/lib/asciidoctor/ietf/converter.rb:118:in `cleanup'
	17: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/cleanup.rb:43:in `cleanup'
	16: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/cleanup_ref.rb:153:in `bibitem_cleanup'
	15: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/cleanup_ref_dl.rb:8:in `ref_dl_cleanup'
	14: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
	13: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
	12: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
	11: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.9.3/lib/asciidoctor/standoc/cleanup_ref_dl.rb:11:in `block in ref_dl_cleanup'
	10: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/bibliographic_item.rb:263:in `from_hash'
	 9: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:25:in `hash_to_bib'
	 8: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:180:in `contributors_hash_to_bib'
	 7: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:180:in `each_with_index'
	 6: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:180:in `each'
	 5: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:192:in `block in contributors_hash_to_bib'
	 4: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:215:in `person_hash_to_bib'
	 3: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:229:in `fullname_hash_to_bib'
	 2: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:470:in `localname'
	 1: from /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/hash_converter.rb:470:in `new'
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/relaton-bib-1.8.1/lib/relaton_bib/localized_string.rb:26:in `initialize': invalid LocalizedString content type: String (ArgumentError)
```

**Comment by opoudjis** [comment]
I can't get this document to compile to begin with, but I have a substantially updated version in metanorma-ietf/spec/examples/antioch.adoc (2020 as opposed to 2018), which compiles (and is in Metanorma Asciidoctor, not the old AsciiRFC), and which does not differ in content. I'm just going to overwrite the document here with that.

**Comment by ronaldtse** [comment]
@opoudjis when you say "replace" please do so in the context of this PR.

**Comment by opoudjis** [comment]
Am doing so.

Doc is compiling, but now xml2rfc is barfing on SVG. The SVG is one found in the wild, but I will try and find a compliant one to IETF's narrow profile.

**Comment by opoudjis** [comment]
Also having to deal with Data URIs in SVG: https://github.com/metanorma/metanorma-ietf/issues/152

**Comment by opoudjis** [comment]
Will not compile without metanorma/metanorma-ietf#152 published into released gem. Due in a week.

**Pull request merged**
